### PR TITLE
Add missing sync function signatures to types

### PR DESCRIPTION
**Pull request by Darkle**
Add missing sync function signatures to types

### CODE REVIEW

**Comment by nikitaeverywhere** [comment]
Hello! Thanks for your contribution.

For better readability, I suggest to please declare this type:

```ts
type Handler<returnType = void> = () => Promise<returnType> | returnType;
```

And then say `handler: Handler` everywhere. It's likely the return type might be used one day, thus it will be a single place to change it.

**Comment by Darkle** [comment]
Done.

**Comment by nikitaeverywhere** [comment]
Thanks @Darkle! It's now out in version 1.1.3.

**Comment by nikitaeverywhere** [comment]
Yay, I merged invalid TS syntax. Wondering why didn't it break in your project?

**Comment by nikitaeverywhere** [comment]
See #9

**Pull request merged**
