### PR TITLE
tech/refactor getAllDependents func to be more performant

### PR DESCRIPTION
**Pull request by burnerx47**
**Issue:**
When you have a lot of dependencies functions runs 3 times on the same collection.
**Solution:**
It can be optimized by using reduce

### CODE REVIEW

**Comment by nikitaeverywhere** [comment]
Hi Mike! Nice to see you here! :) 

Regarding your PR, I LOVE REFACTORING PRs 😃 (no)

Why do you need performance, if the dependency tree is usually no more than 10 elements? Here I would prefer readability over performance.

**Comment by nikitaeverywhere** [comment]
What you can optimize though is to use one `filter` instead of two. Watch out mixed 2/4 spaces in your PR.

**Comment by burnerx47** [comment]
Thanks for your feedback! I updated PR.

**Comment by burnerx47** [comment]
@ZitRos Maybe we can rewrite this code into TS? Do you like that idea?

**Comment by nikitaeverywhere** [comment]
@mikerudenko, I don't like the idea of rewriting something just to rewrite it. I'm not against adding `typings.d.ts` though, but let's keep the original code.

Regarding your refactoring, please keep `!== -1` instead of `~` 👼 (as it is more readable), or simply switch to `.includes()` as it's node `6.17.1+` which is pretty old (btw breaking change, so I would prefer `!==`). But still, I don't like the idea of changing something just because we can 🤔 It's a mutual time-wasting.

**Comment by nikitaeverywhere** [comment]
Closed due to inactivity.

**Pull request closed without merging**
