### PR TITLE
Add function to run exit logic without exiting (for testing scenarios)

### PR DESCRIPTION
**Pull request by nordfjord**
- feat: Expose 'performShutdown' method to enable testing scenarios
- chore: Improve typescript typings

### CODE REVIEW

**Comment by nikitaeverywhere** [comment]
Hello! Thanks for your contribution.

1. I agree to improve typings.
2. I don't understand what's the point in "enable testing scenarios".
   + If you're writing an application using `node-graceful-shutdown` and you want to test how it shuts down, you can find a more clever way to do this in your testing code; changing the code of the library is an anti-pattern. For instance if you want to test that your application writes something to a database on shutdown, you need to actually shut down you application and query the database. If you want just to mock `performShutdown` function, mock `process.exit` instead.
   + If you want to ensure this library works as it's supposed to, please contribute to this library's tests instead.

**Comment by nordfjord** [comment]
> I don't understand what's the point in "enable testing scenarios"

Let me give a concrete example:

```ts
// database.ts
const pool = pg.Pool(...)

onShutdown('database', ()=> pool.close())
```

```ts
// feature.spec.ts
test('it does stuff', async ()=> {
 await service.doStuff()
  expect(await service.stuff()).toEqual(...)
})
```

In the above example a testing tool like `jest` will not forcefully exit the process as there will be a dangling connection.

One way to work around it is:

```ts
afterAll(()=> process.emit('SIGQUIT'))
```

But this would potentially exit the process before `jest` has time to render the final output to the terminal.

I think your suggestion is to mock process.exit like so:

```ts
afterAll(()=> {
  const _exit = process.exit
  return new Promise((resolve, reject) => {
    process.exit = (code)=> code === 0 ? resolve(code) : reject(code)
    process.emit('SIGQUIT')
  })
  .finally(()=> (process.exit = _exit))
})
```

My problem with doing this is that I'd be coupling my testing to knowledge about the underlying assumptions of your library (that it listens to `SIGQUIT`, and will call `process.exit`)

What this proposed change does is allow users to execute the shutdown logic without having to know about the inner details of the wiring of the library.

**Comment by nikitaeverywhere** [comment]
Sorry for the long waiting time, was really busy.

> In the above example a testing tool like jest will not forcefully exit the process as there will be a dangling connection.

1. Is there anything that prevents you from **not** using [jest --forceExit](https://jestjs.io/docs/cli#--forceexit)?
2. If Jest does not exit normally without `--forceExit`, it means you are not closing all the connections properly in your app which you test, hence you're misusing `node-graceful-shutdown`, right?

**Comment by nordfjord** [comment]
On your first question:

I am not using --forceExit (the docs describe it as an escape hatch)

On your second question:

Jest will not issue any signal that your library would pick up. With this patch I can call `performShutdown` and my test will exit normally. If it doesn't that indicates as you point out that I'm not capturing all dangling resources with `node-graceful-shutdown` (a useful thing to know in my opinion)

**Comment by nikitaeverywhere** [comment]
> Jest will not issue any signal that your library would pick up.

I would consider this as a bug in the library, which we need to fix instead. How does jest exits the process? `process.exit`?

**Comment by nikitaeverywhere** [comment]
FYI renamed the `master` branch to be `main`, please consider re-opening PR. We can continue a discussion here if you want.

**Comment by tayler-king** [comment]
> On your first question:
> 
> I am not using --forceExit (the docs describe it as an escape hatch)
> 
> On your second question:
> 
> Jest will not issue any signal that your library would pick up. With this patch I can call `performShutdown` and my test will exit normally. If it doesn't that indicates as you point out that I'm not capturing all dangling resources with `node-graceful-shutdown` (a useful thing to know in my opinion)

Given that the library itself has a test suite, have you considered testing your individual shutdown handlers instead of testing the library's execution of the shutdown handlers?

Instead of testing your example:

```js
// database.ts
const pool = pg.Pool(...)

onShutdown('database', () => pool.close())
```

Instead, test the `handleShutdown()` function:

```js
// database.ts
const pool = pg.Pool(...)
const handleShutdown = () => pool.close()

onShutdown('database', handleShutdown)
```

**Pull request closed without merging**
